version: "2"
services:
  flask:
    image: "liubai01/liubaihome:prod"
    container_name: "flask-web"
    ports:
      - "8000:8000"
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server_data/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./server_data/nginx/docs:/usr/share/nginx/docs
      - ./server.crt:/etc/nginx/certs/server.crt
      - ./server.key:/etc/nginx/certs/server.key