version: "2"
services:
  flask:
    image: "liubai01/liubaihome:prod"
    container_name: "flask-web"
    ports:
      - "8000:8000"
  nextcloud:
    image: "nextcloud"
    container_name: "nextcloud"
    volumes:
      - ./server_data/nextcloud/config:/var/www/html/config
      - ./server_data/nextcloud/data:/var/www/html/data
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./server_data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./server_data/nginx/default.conf:/etc/nginx/conf.d/default.conf