name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: liubai01/liubaihome:latest

      - name: Extract SSL Certificate
        run: |
          echo "${{ secrets.SSL_CRT }}" > server.crt
          echo "${{ secrets.SSL_KEY }}" > server.key

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: liubai01/liubaihome:latest

      - name: Start the Container (SSL)
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.TENCENT_CLOUD_IP }}
            username: ${{ secrets.TENCENT_CLOUD_NAME }}
            password: ${{ secrets.TENCENT_CLOUD_PASSWORD }}
            script: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} || docker rm -f flaskweb || docker pull liubai01/liubaihome:latest && docker run -it -d -p 443:8000 --name flaskweb liubai01/liubaihome:latest